apiVersion: apps/v1
kind: Deployment
metadata:
  name: gb-ui2
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: gb-ui2
  template:
    metadata:
      labels:
        app: gb-ui2
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: gb-ui2
        ports:
        - containerPort: 80
